version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: dbname
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/postgresql/focusco-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  focusco-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/frontend:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - focusco-backend

volumes:
  db-data: