get http://localhost:3000/api/messages/schedule HTTP/1.1
content-type: application/json

{
}
###

DELETE http://localhost:3000/api/users HTTP/1.1

###

POST http://localhost:3000/api/auth/passcode HTTP/1.1
content-type: application/json

{
    "passcode": "123"
}
###
POST http://localhost:3000/api/messages/webhook HTTP/1.1
content-type: application/json

{
    "From": "+16196037721",
    "To": "+18444362879",
    "Body": "123"
}

###

GET http://localhost:3000/api/users HTTP/1.1


GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json


###
GET http://localhost:3000/users HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Owner",
    "number": "+18444362879",
    "isOwner": true
}

###
GET http://localhost:3000/users HTTP/1.1


### 
// create a message between user ID 5 and user ID 4
POST http://localhost:3000/api/auth/passcode HTTP/1.1
content-type: application/json

{
    "passcode": "123"
}

###
GET http://localhost:3000/messages/schedule HTTP/1.1

###
DELETE http://localhost:3000/messages/schedule HTTP/1.1
