GET http://localhost:3000/users HTTP/1.1
content-type: application/json

{
}
###
PUT http://localhost:3000/users/2 HTTP/1.1
content-type: application/json

{
    "isOwner": true
}

###
DELETE http://localhost:3000/users HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "name": "Owner",
    "number": "+15561238888"
}

###
GET http://localhost:3000/users HTTP/1.1


### 
// create a message between user ID 5 and user ID 4
POST http://localhost:3000/auth/check HTTP/1.1
content-type: application/json

{
    "passcode": "HHkTWsCTmF6hyh5"
}

###
GET http://localhost:3000/messages/schedule HTTP/1.1

###
DELETE http://localhost:3000/messages/schedule HTTP/1.1
